{%set version = "0.9" %}

package:
  name: begins
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/begins/begins-{{ version }}.tar.gz
  sha256: 98864dc7593ce438074ed30e4c030dcb37e795376726d9150d557ed9d868ef55

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - setuptools

test:
  imports:
    - begin

about:
  home: http://begins.readthedocs.org
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Command line programs for busy developers'
  doc_url: http://begins.readthedocs.org
  dev_url: https://github.com/aliles/begins

extra:
  recipe-maintainers:
    - pmlandwehr
