travis:
  secure:
    BINSTAR_TOKEN: wGfdvvI7ADap0XGaVLt1b5tvnEVYRSd/xLiLksIqAk/rm76tiF0cRvUq6Nkwh/CVtvgSXGmOqLfZMs+BIlwfkHUeAsIk7ytOgbEfLDtvaYZqUooAuoK8JDvotSdkfaDCRbZuiqAudLIMOxvp6ymWN6OE/2ZtgX0ITlOo+9C8uEROjN92Fl24aXLEZl57choiKltgwLjHOCcClGWe6KFIMU3tM9MmGrJqhz2j/jkEoOlbNj0/10lSGgGqWXQzBRvgAf65oSyhhspP0Mc8ZdPCtJPSixPQNCX/phV73XBMlc1kA7r9KZQqwaQpn1XHV0ShaQqR+69v5EXVjX9jsTnIehoQ7A1+0s2ffEkN+J6Dy1Ys4yQf1aQQOWsR1QSOQYkJig6uK6FTWUe/eSqEefkkFDljRzJe7au8r0usxgAGl2+NxhfzsEc3ys4dsTw0xH/DurFLE9+WxGArXKQCG4jF80JuxXA+UlCmFoefiy+jxCxReGUd+XRifQUPjdFj29Tco8+gp9kE5/z0pk7XPc+KFR5VHqVWjEKMn+tFDrtKNC3MSVCGjte+FvkS/LjUCg3pN6Bjn5gtv6MqFAjKsyfEylm3lIJDzTR79FirZl8u+f61zuvgQyWvhgekhokHneJm1Kn95M6WKsI8v+Dsz4M1IH3oSMqmClnBwOB2N9ueatM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
