travis:
  secure:
    BINSTAR_TOKEN: e+eFifNvRL54N8J1kv6pQarHpdZVQRNEn/69r+O2ArBKO1xOSPks+KNd9n3c+AkLek3inNHKHlBDjM3ltmKOZyItjFj6VTjObrHaxSa9YtMFYBZsdSlY+ajJ79rPty6NGy+gvz8rtzoGPqAJwONVdm/GyY9rzvigZ+AcitJeHVDk9us2+TpatkjPjpvYQbj7CkTNGDJDSXaktO/+wNz+xHsKGJcWyfG8BOJ4X6fmTSMLNRTgz9OzwVhaWfbuQadsT3zjVJx6sqlE9ZePlipHAHLQU0AUy/kn+2TKct5yijfyBi75JnZhGILF+mFIrabDBxYsyqJE2Km3zUYya6eI6Z2IjxqK8y/KVZ2fwzplu2F/2jTHtG6Uh3FLLTPMKGyxIfuSuKrObjh9IGA9f6lk2cakxOB8beQNjslzxLeIder8RfShB0ib0yUM5lJ8MVHa3DKjYWD/4KJq6aonKWeJ8Y58S7zER0AGm0txeo9isRUwxT9zYju4gf1TG2cw5/y9EJv8eh3xTDhFToLQpBGxHz9Im3bsDevbF+wTdlUb3UoMFKl1oCCMlQqtwC7iBA9BGJ872zbNhUI+9OzIcFH3CegQyOudaI4K6xQa/y+RPN7P5oJ+wA3Cbb16BUZYG8CrB1dqI/TEsPWloU8MHOd5uqAodrSzG6yjr+PBlwJBsNk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
